### ISSUE TITLE
The config service is failing with 502 Bad Gateway [Transient-SDS Deployments]

### ISSUE THREAD

**Issue by isaac-dasan** [Azure/remote-monitoring-services-java#137]
# Type of issue 
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description 
The config service is the one responsible for adding the correct Document DB collections, which ASA relies on.
![image](https://user-images.githubusercontent.com/22013837/56997560-0a45fc00-6b5d-11e9-8b83-c35f6939656d.png)

In looking at the logs for the **Config service** on the vm you see:

54) Error injecting constructor, com.microsoft.azure.keyvault.models.KeyVaultErrorException: Status code 401,
  at com.microsoft.azure.iotsolutions.uiconfig.webservice.runtime.Config.<init>(Config.java:49)
  at com.microsoft.azure.iotsolutions.uiconfig.webservice.runtime.Config.class(Config.java:18)
  while locating com.microsoft.azure.iotsolutions.uiconfig.webservice.runtime.Config
  while locating com.microsoft.azure.iotsolutions.uiconfig.webservice.runtime.IConfig
    for the 1st parameter of Module.provideIServicesConfig(Module.java:34)
  while locating com.microsoft.azure.iotsolutions.uiconfig.services.runtime.IServicesConfig
    for the 2nd parameter of com.microsoft.azure.iotsolutions.uiconfig.services.external.StorageAdapterClient.<init>(StorageAdapterClient.java:36)
  while locating com.microsoft.azure.iotsolutions.uiconfig.services.external.StorageAdapterClient
  while locating com.microsoft.azure.iotsolutions.uiconfig.services.external.IStorageAdapterClient
    for the 4th parameter of com.microsoft.azure.iotsolutions.uiconfig.services.Seed.<init>(Seed.java:52)
  at com.microsoft.azure.iotsolutions.uiconfig.services.Seed.class(Seed.java:32)
  while locating com.microsoft.azure.iotsolutions.uiconfig.services.Seed
  while locating com.microsoft.azure.iotsolutions.uiconfig.services.ISeed
Caused by: com.microsoft.azure.keyvault.models.KeyVaultErrorException (same stack trace as error #48)
55) Error injecting constructor, com.microsoft.azure.keyvault.models.KeyVaultErrorException: Status code 401,
  at com.microsoft.azure.iotsolutions.uiconfig.webservice.runtime.Config.<init>(Config.java:49)
  at com.microsoft.azure.iotsolutions.uiconfig.webservice.runtime.Config.class(Config.java:18)
  while locating com.microsoft.azure.iotsolutions.uiconfig.webservice.runtime.Config
  while locating com.microsoft.azure.iotsolutions.uiconfig.webservice.runtime.IConfig
    for the 1st parameter of Module.provideIServicesConfig(Module.java:34)
  while locating com.microsoft.azure.iotsolutions.uiconfig.services.runtime.IServicesConfig
    for the 2nd parameter of com.microsoft.azure.iotsolutions.uiconfig.services.external.DeviceSimulationClient.<init>(DeviceSimulationClient.java:25)
  at com.microsoft.azure.iotsolutions.uiconfig.services.external.DeviceSimulationClient.class(DeviceSimulationClient.java:17)
  while locating com.microsoft.azure.iotsolutions.uiconfig.services.external.DeviceSimulationClient
  while locating com.microsoft.azure.iotsolutions.uiconfig.services.external.IDeviceSimulationClient
    for the 5th parameter of com.microsoft.azure.iotsolutions.uiconfig.services.Seed.<init>(Seed.java:52)
  at com.microsoft.azure.iotsolutions.uiconfig.services.Seed.class(Seed.java:32)
  while locating com.microsoft.azure.iotsolutions.uiconfig.services.Seed
  while locating com.microsoft.azure.iotsolutions.uiconfig.services.ISeed
Caused by: com.microsoft.azure.keyvault.models.KeyVaultErrorException (same stack trace as error #53)
56) Error injecting constructor, com.microsoft.azure.keyvault.models.KeyVaultErrorException: Status code 401,
  at com.microsoft.azure.iotsolutions.uiconfig.webservice.runtime.Config.<init>(Config.java:49)
  at com.microsoft.azure.iotsolutions.uiconfig.webservice.runtime.Config.class(Config.java:18)
  while locating com.microsoft.azure.iotsolutions.uiconfig.webservice.runtime.Config
  while locating com.microsoft.azure.iotsolutions.uiconfig.webservice.runtime.IConfig
    for the 1st parameter of Module.provideIServicesConfig(Module.java:34)
  while locating com.microsoft.azure.iotsolutions.uiconfig.services.runtime.IServicesConfig
    for the 2nd parameter of com.microsoft.azure.iotsolutions.uiconfig.services.external.DeviceTelemetryClient.<init>(DeviceTelemetryClient.java:24)
  at com.microsoft.azure.iotsolutions.uiconfig.services.external.DeviceTelemetryClient.class(DeviceTelemetryClient.java:24)
  while locating com.microsoft.azure.iotsolutions.uiconfig.services.external.DeviceTelemetryClient
  while locating com.microsoft.azure.iotsolutions.uiconfig.services.external.IDeviceTelemetryClient
    for the 6th parameter of com.microsoft.azure.iotsolutions.uiconfig.services.Seed.<init>(Seed.java:52)
  at com.microsoft.azure.iotsolutions.uiconfig.services.Seed.class(Seed.java:32)
  while locating com.microsoft.azure.iotsolutions.uiconfig.services.Seed
  while locating com.microsoft.azure.iotsolutions.uiconfig.services.ISeed
Caused by: com.microsoft.azure.keyvault.models.KeyVaultErrorException (same stack trace as error #53)
56 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
        at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
        at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:51)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
[info] a.a.CoordinatedShutdown - Starting coordinated shutdown from JVM shutdown hook

 

There are actually 3 services that have exited with failures:
![image](https://user-images.githubusercontent.com/22013837/56997573-16ca5480-6b5d-11e9-8f6b-8cc5e6b2ee35.png)

**Telemetry Service Error:**

26) Error injecting constructor, com.microsoft.azure.keyvault.models.KeyVaultErrorException: Status code 401,
  at com.microsoft.azure.iotsolutions.devicetelemetry.webservice.runtime.Config.<init>(Config.java:85)
  at com.microsoft.azure.iotsolutions.devicetelemetry.webservice.runtime.Config.class(Config.java:22)
  while locating com.microsoft.azure.iotsolutions.devicetelemetry.webservice.runtime.Config
  while locating com.microsoft.azure.iotsolutions.devicetelemetry.webservice.runtime.IConfig
Caused by: com.microsoft.azure.keyvault.models.KeyVaultErrorException: Status code 401,
        at sun.reflect.GeneratedConstructorAccessor39.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
        at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
        at com.microsoft.azure.keyvault.implementation.KeyVaultClientBaseImpl.getSecretsDelegate(KeyVaultClientBaseImpl.java:4147)
        at com.microsoft.azure.keyvault.implementation.KeyVaultClientBaseImpl.access$2300(KeyVaultClientBaseImpl.java:120)
        at com.microsoft.azure.keyvault.implementation.KeyVaultClientBaseImpl$108.call(KeyVaultClientBaseImpl.java:4018)
        at com.microsoft.azure.keyvault.implementation.KeyVaultClientBaseImpl$108.call(KeyVaultClientBaseImpl.java:4014)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
        at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
        at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
        at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
        at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
        at rx.Observable.unsafeSubscribe(Observable.java:10142)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:10238)
        at rx.Observable.subscribe(Observable.java:10205)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:444)
        at rx.observables.BlockingObservable.single(BlockingObservable.java:341)
        at com.microsoft.azure.keyvault.implementation.KeyVaultClientBaseImpl.getSecrets(KeyVaultClientBaseImpl.java:3926)
        at com.microsoft.azure.keyvault.implementation.KeyVaultClientCustomImpl.listSecrets(KeyVaultClientCustomImpl.java:1176)
        at com.microsoft.azure.iotsolutions.devicetelemetry.services.runtime.KeyVault.getAllKeys(KeyVault.java:145)
        at com.microsoft.azure.iotsolutions.devicetelemetry.services.runtime.KeyVault.<init>(KeyVault.java:41)
        at com.microsoft.azure.iotsolutions.devicetelemetry.services.runtime.ConfigData.setUpKeyVault(ConfigData.java:186)
        at com.microsoft.azure.iotsolutions.devicetelemetry.services.runtime.ConfigData.<init>(ConfigData.java:37)
        at com.microsoft.azure.iotsolutions.devicetelemetry.webservice.runtime.Config.<init>(Config.java:86)
        at com.microsoft.azure.iotsolutions.devicetelemetry.webservice.runtime.Config$$FastClassByGuice$$47cded84.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:759)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
        at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
        at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:51)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)

26 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
        at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
        at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:51)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
[info] a.a.CoordinatedShutdown - Starting coordinated shutdown from JVM shutdown hook

 

**IoT Hub Manager:**

35) Error injecting constructor, com.microsoft.azure.keyvault.models.KeyVaultErrorException: Status code 401,
  at com.microsoft.azure.iotsolutions.iothubmanager.webservice.runtime.Config.<init>(Config.java:51)
  at com.microsoft.azure.iotsolutions.iothubmanager.webservice.runtime.Config.class(Config.java:23)
  while locating com.microsoft.azure.iotsolutions.iothubmanager.webservice.runtime.Config
  while locating com.microsoft.azure.iotsolutions.iothubmanager.webservice.runtime.IConfig
    for the 1st parameter of Module.provideIServicesConfig(Module.java:34)
  while locating com.microsoft.azure.iotsolutions.iothubmanager.services.runtime.IServicesConfig
    for the 1st parameter of com.microsoft.azure.iotsolutions.iothubmanager.services.IoTHubWrapper.<init>(IoTHubWrapper.java:32)
  while locating com.microsoft.azure.iotsolutions.iothubmanager.services.IoTHubWrapper
  while locating com.microsoft.azure.iotsolutions.iothubmanager.services.IIoTHubWrapper
    for the 1st parameter of com.microsoft.azure.iotsolutions.iothubmanager.services.Devices.<init>(Devices.java:72)
  while locating com.microsoft.azure.iotsolutions.iothubmanager.services.Devices
  while locating com.microsoft.azure.iotsolutions.iothubmanager.services.IDevices
    for the 3rd parameter of com.microsoft.azure.iotsolutions.iothubmanager.services.DeviceProperties.<init>(DeviceProperties.java:57)
  at com.microsoft.azure.iotsolutions.iothubmanager.services.DeviceProperties.class(DeviceProperties.java:34)
  while locating com.microsoft.azure.iotsolutions.iothubmanager.services.DeviceProperties
  while locating com.microsoft.azure.iotsolutions.iothubmanager.services.IDeviceProperties
Caused by: com.microsoft.azure.keyvault.models.KeyVaultErrorException: Status code 401,
        at sun.reflect.GeneratedConstructorAccessor38.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
        at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
        at com.microsoft.azure.keyvault.implementation.KeyVaultClientBaseImpl.getSecretsDelegate(KeyVaultClientBaseImpl.java:4147)
        at com.microsoft.azure.keyvault.implementation.KeyVaultClientBaseImpl.access$2300(KeyVaultClientBaseImpl.java:120)
        at com.microsoft.azure.keyvault.implementation.KeyVaultClientBaseImpl$108.call(KeyVaultClientBaseImpl.java:4018)
        at com.microsoft.azure.keyvault.implementation.KeyVaultClientBaseImpl$108.call(KeyVaultClientBaseImpl.java:4014)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
        at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
        at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
        at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
        at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
        at rx.Observable.unsafeSubscribe(Observable.java:10142)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:10238)
        at rx.Observable.subscribe(Observable.java:10205)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:444)
        at rx.observables.BlockingObservable.single(BlockingObservable.java:341)
        at com.microsoft.azure.keyvault.implementation.KeyVaultClientBaseImpl.getSecrets(KeyVaultClientBaseImpl.java:3926)
        at com.microsoft.azure.keyvault.implementation.KeyVaultClientCustomImpl.listSecrets(KeyVaultClientCustomImpl.java:1176)
        at com.microsoft.azure.iotsolutions.iothubmanager.services.runtime.KeyVault.getAllKeys(KeyVault.java:145)
        at com.microsoft.azure.iotsolutions.iothubmanager.services.runtime.KeyVault.<init>(KeyVault.java:41)
        at com.microsoft.azure.iotsolutions.iothubmanager.services.runtime.ConfigData.setUpKeyVault(ConfigData.java:234)
        at com.microsoft.azure.iotsolutions.iothubmanager.services.runtime.ConfigData.<init>(ConfigData.java:38)
        at com.microsoft.azure.iotsolutions.iothubmanager.webservice.runtime.Config.<init>(Config.java:54)
        at com.microsoft.azure.iotsolutions.iothubmanager.webservice.runtime.Config$$FastClassByGuice$$d89367c7.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:759)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:402)
        at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:759)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:759)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:759)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
        at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
        at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:51)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)

36) Error injecting constructor, com.microsoft.azure.keyvault.models.KeyVaultErrorException: Status code 401,
  at com.microsoft.azure.iotsolutions.iothubmanager.webservice.runtime.Config.<init>(Config.java:51)
  at com.microsoft.azure.iotsolutions.iothubmanager.webservice.runtime.Config.class(Config.java:23)
  while locating com.microsoft.azure.iotsolutions.iothubmanager.webservice.runtime.Config
  while locating com.microsoft.azure.iotsolutions.iothubmanager.webservice.runtime.IConfig
    for the 1st parameter of Module.provideIServicesConfig(Module.java:34)
  while locating com.microsoft.azure.iotsolutions.iothubmanager.services.runtime.IServicesConfig
    for the 2nd parameter of com.microsoft.azure.iotsolutions.iothubmanager.services.external.StorageAdapterClient.<init>(StorageAdapterClient.java:23)
  while locating com.microsoft.azure.iotsolutions.iothubmanager.services.external.StorageAdapterClient
  while locating com.microsoft.azure.iotsolutions.iothubmanager.services.external.IStorageAdapterClient
    for the 2nd parameter of com.microsoft.azure.iotsolutions.iothubmanager.services.Devices.<init>(Devices.java:72)
  while locating com.microsoft.azure.iotsolutions.iothubmanager.services.Devices
  while locating com.microsoft.azure.iotsolutions.iothubmanager.services.IDevices
    for the 3rd parameter of com.microsoft.azure.iotsolutions.iothubmanager.services.DeviceProperties.<init>(DeviceProperties.java:57)
  at com.microsoft.azure.iotsolutions.iothubmanager.services.DeviceProperties.class(DeviceProperties.java:34)
  while locating com.microsoft.azure.iotsolutions.iothubmanager.services.DeviceProperties
  while locating com.microsoft.azure.iotsolutions.iothubmanager.services.IDeviceProperties
Caused by: com.microsoft.azure.keyvault.models.KeyVaultErrorException (same stack trace as error #35)
36 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
        at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
        at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:51)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
[info] a.a.CoordinatedShutdown - Starting coordinated shutdown from JVM shutdown hook

**Comment by isaac-dasan** [comment]
Please talk to someone in SA SDS team to gain access to zachtestingsolutiontlNap  zachtestingsolutionjS4tc

**Comment by ppathan** [comment]
This is SDS related and the fix is being worked on.

**Comment by ppathan** [comment]
Issue is fixed in SDS
