### ISSUE TITLE
DocumentClientFactory should use IServicesConfig in constructor

### ISSUE THREAD

**Issue by sushilraje** [Azure/remote-monitoring-services-java#19]
<a href="https://github.com/zhang-hua"><img src="https://avatars1.githubusercontent.com/u/2011059?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zhang-hua](https://github.com/zhang-hua)**
_Thursday Nov 30, 2017 at 09:09 GMT_
_Originally opened as https://github.com/Azure/pcs-storage-adapter-java/issues/50_

----

# Type of issue 

- [x] Bug
- [ ] New feature
- [x] Enhancement

# Description 

https://github.com/Azure/pcs-storage-adapter-java/blob/master/app/com/microsoft/azure/iotsolutions/storageadapter/services/wrappers/DocumentClientFactory.java#L28

**Comment by sushilraje** [comment]
<a href="https://github.com/jwendl"><img src="https://avatars1.githubusercontent.com/u/1068431?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jwendl](https://github.com/jwendl)**
_Saturday Jun 02, 2018 at 01:34 GMT_

----

Hello @zhang-hua - would this also impact being able to do the following?

``` bash
export PCS_STORAGEADAPTER_CONTAINER_NAME="..."
./scripts/build
```

And getting the error (note the null docDbEndpoint)

```
[info] Test com.microsoft.azure.iotsolutions.storageadapter.service.DocDBKeyValueContainerTest.putTest started
[error] Test com.microsoft.azure.iotsolutions.storageadapter.service.DocDBKeyValueContainerTest.putTest failed: com.microsoft.azure.iotsolutions.storageadapter.services.exceptions.InvalidConfigurationException: DocumentDB configuration error, took 0.223 sec
[error] c.m.a.i.s.s.w.DocumentClientFactory - Config: 'docDbEndpoint'=, 'docDbKey'=, 'databaseName'=pcs-storage, 'collectionId'=pcs-storage
[error]     at com.microsoft.azure.iotsolutions.storageadapter.services.wrappers.DocumentClientFactory.<init>(DocumentClientFactory.java:41)
[error] c.m.a.i.s.s.w.DocumentClientFactory - Config: 'docDbEndpoint'=, 'docDbKey'=, 'databaseName'=pcs-storage, 'collectionId'=pcs-storage
[error] c.m.a.i.s.s.w.DocumentClientFactory - Config: 'docDbEndpoint'=, 'docDbKey'=, 'databaseName'=pcs-storage, 'collectionId'=pcs-storage
[error] c.m.a.i.s.s.w.DocumentClientFactory - Config: 'docDbEndpoint'=, 'docDbKey'=, 'databaseName'=pcs-storage, 'collectionId'=pcs-storage
[error]     at com.microsoft.azure.iotsolutions.storageadapter.service.DocDBKeyValueContainerTest.setUp(DocDBKeyValueContainerTest.java:39)
[error]     ...
[error] Test com.microsoft.azure.iotsolutions.storageadapter.service.DocDBKeyValueContainerTest.putTest failed: java.lang.NullPointerException: null, took 0.224 sec
[error]     at com.microsoft.azure.iotsolutions.storageadapter.service.DocDBKeyValueContainerTest.tearDown(DocDBKeyValueContainerTest.java:47)
[error]     ...
```

Or is this unrelated?

**Comment by sushilraje** [comment]
<a href="https://github.com/zhang-hua"><img src="https://avatars1.githubusercontent.com/u/2011059?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zhang-hua](https://github.com/zhang-hua)**
_Sunday Jun 03, 2018 at 16:08 GMT_

----

@jwendl , it is unrelated. please export another environment variable for document db connection before running tests:
```
export PCS_STORAGEADAPTER_DOCUMENTDB_CONNSTRING="..."
```
